name: leancloud_flutter_plugin
description: LeanCloud flutter plugin by Luna Gao
version: 0.0.1
author: Luna Gao <gao.xue.qi@qq.com>
homepage: https://github.com/LunaGao/leancloud_flutter_plugin

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.lunagao.leancloudflutterplugin
    pluginClass: LeancloudFlutterPlugin
